

image: maven:3-jdk-8-alpine

before_script:
  - apk update && apk add bash coreutils git docker
  - docker info

variables:
  GRADLE_OPTS: "-Dcrafter.git.shallowClone=true"
  GRADLE_USER_HOME: "/cache/.gradle"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository -DinteractiveMode=false"
  TERM: dumb

build:
  script:
    - ./gradlew init build deploy
    - ./docker/prepare authoring
    - ./docker/prepare delivery
    - ./docker/build authoring
    - ./docker/build delivery
  cache:
    paths:
      - downloads/



