
image: docker:stable

variables:
  GRADLE_OPTS: "-Dcrafter.git.shallowClone=true"
  GRADLE_USER_HOME: "/cache/.gradle"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  TERM: dumb

stages:
  - bootstrap
  - build
  - docker config
  - docker


prepare craftercms build image:
  stage: bootstrap
  script: docker build --pull -t craftercms/build-image docker/build

build crafter:
  image: craftercms/build-image
  stage: build
  script: ./gradlew init build deploy
  cache:
    paths:
      - .m2/
      - downloads/
  artifacts:
    paths:
      - crafter-authoring/
      - crafter-delivery/

#package crafter:
#  stage: package
#  script: ./gradlew deploy

create docker config:
  stage: docker config
  before_script:
    - apk update
    - apk add bash
  script: ./docker/prepare

docker authoring:
  stage: docker
  before_script:
    - apk update
    - apk add bash
  script: ./docker/build authoring

docker delivery:
  stage: docker
  before_script:
    - apk update
    - apk add bash
  script: ./docker/build delivery
