#!/usr/bin/env bash

set -euECo pipefail

declare -r CRAFTER_JRE=docker-harbor1.support.ecom.thalia.de/red/crafter-jre

# build the crafter-jre image if needed
if ! docker inspect -f '{{.Id}}' "$CRAFTER_JRE" &> /dev/null; then
    docker build --pull -t "$CRAFTER_JRE" docker/jre
fi

cp -ft crafter-authoring docker/authoring/Dockerfile docker/authoring/supervisor.conf docker/docker-crafter

cp -ft crafter-delivery docker/delivery/Dockerfile docker/delivery/supervisor.conf docker/docker-crafter
