#!/usr/bin/env bash

set -euECo pipefail

declare -r CRAFTER_JRE=docker-harbor1.support.ecom.thalia.de/red/crafter-jre

# build the crafter-jre image if needed
if ! docker inspect -f '{{.Id}}' "$CRAFTER_JRE" &> /dev/null; then
    docker build --pull -t "$CRAFTER_JRE" docker/jre
fi

declare -r CRAFTER_ENV="$1"

cp -ft crafter-$CRAFTER_ENV docker/$CRAFTER_ENV/Dockerfile docker/$CRAFTER_ENV/supervisor.conf
cp -ft crafter-$CRAFTER_ENV/bin docker/docker-crafter
