#!/usr/bin/env bash

set -euECo pipefail

declare -r CRAFTER_VERSION=$( sed -n -e 's/^ *project.version *= *"*\([0-9.]*\).*/\1/p' -e t build.gradle )
declare -r TARGET="cms$1"
declare -r IMAGE="docker-harbor1.support.ecom.thalia.de/cms/$TARGET:${CRAFTER_VERSION:-$CI_COMMIT_REF_SLUG}"

docker push "$IMAGE"
