#!/usr/bin/env bash

set -euECo pipefail

declare -r NAME="$1"
declare -r IMAGE="$2"
declare -r ENV="$3"
declare -r DATA_DIR=/opt/crafter/data
declare -r LOGS_DIR=/opt/crafter/logs

if [ ! -d "$DATA_DIR" ]; then
    mkdir -p "$DATA_DIR"
fi

echo "Pull image $IMAGE"
docker pull "$IMAGE"
echo "Stop and remove container in case it is running $NAME"
docker stop "$NAME" || : ok
docker rm -v "$NAME" || : ok


echo "Create new container $NAME"
if [ "$NAME" = cmsdelivery ]; then
    docker create --name "$NAME" -v "$DATA_DIR":/opt/crafter/data/ -v "$LOGS_DIR":/opt/crafter/logs/ --restart=unless-stopped -p 9080:9080 -p 8695:8695 "$IMAGE"
else
    if [ "$ENV" = dev ]; then
        docker create --name "$NAME" -v "$DATA_DIR":/opt/crafter/data/ -v "$LOGS_DIR":/opt/crafter/logs/ --restart=unless-stopped -p 80:8080 -p 8694:8694 -p 33306:33306 "$IMAGE"
    else
        docker create --name "$NAME" -v "$DATA_DIR":/opt/crafter/data/ -v "$LOGS_DIR":/opt/crafter/logs/ --restart=unless-stopped -p 80:8080 -p 8694:8694 "$IMAGE"
    fi
fi

echo "Copy ssh-folder into container"
docker cp .ssh/ "$NAME:/opt/crafter/.ssh/"

echo "Configure site configuration: $ENV-server-config.properties"
docker cp "$NAME:/opt/crafter/bin/apache-tomcat/shared/classes/crafter/engine/extension/$ENV-server-config.properties" server-config.properties
docker cp server-config.properties "$NAME:/opt/crafter/bin/apache-tomcat/shared/classes/crafter/engine/extension/server-config.properties"

echo "Start container $NAME"
docker start "$NAME"

sleep 3 ; docker exec "$NAME" supervisorctl status